version: '3.8'

services:
  db:
    image: postgres:17.4-alpine
    container_name: e-commerce-db
    restart: always
    environment:
      - POSTGRES_DB=e-commerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
volumes:
  db:
    driver: local
